FROM node:slim

# Install git
RUN apt-get -qq update && \
    apt-get -qq install --no-install-recommends \
      git && \
    apt-get -qq autoremove && \
    apt-get -qq autoclean && \
    apt-get -qq clean all && \
    rm -rf /var/cache/apk/*


RUN git clone https://github.com/liside/SuAVE 
WORKDIR SuAVE
RUN npm install

CMD [ "node", "app.js" ]
